# Generated by Django 4.0.2 on 2022-04-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_registration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='telnumber',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
